### ISSUE TITLE
SCORE2 different risk regions

### ISSUE THREAD

**Issue by jandraor** [dvicencio/RiskScorescvd#1]
Hi quick question,

SCORE2 differentiates by risk regions. How do you address that in this package?

Thanks.

**Comment by dvicencio** [comment]
Hi Jair,

Apologies for not explicitly referring to the risk region used in the package.

The SCORE2 function in the ‘RisckScorescvd’ package is limited to the low-risk regions mentioned in the ESC paper.

Therefore, the function has been calibrated for the United Kingdom, Israel, Luxembourg, Switzerland, Spain, Denmark, Belgium, Norway, France, and the Netherlands. 

However, the function could be easily manipulated to add the necessary coefficients/interpretation to address the issue. 

I hope this helps.

All the best,
Dan

**Comment by dvicencio** [comment]
Hi Jair,

As per multiple requests, and I got a little extra time this weekend, I have  updated the Score package with a Risk.region argument/parameter that allows the specification and calculation of different risk regions.

Hope it helps,
Dan

**Comment by jandraor** [comment]
Thank you!
