### ISSUE TITLE
SCORE2 OP Low Risk Region Clarification on Recalibration Scaling

### ISSUE THREAD

**Issue by JauntyJJS** [dvicencio/RiskScorescvd#2]
Hi

I was reading the supplementary word document (attached) of the SCORE2-OP paper to understand how the algorithm was derived.

When I have taken a look at the example at Supplementary Methods Table 3 of a female from a low risk region, I realized that there the recalibration is calculated as follows:

10-yr risk = 1-exp(-exp(**-0.85**+**0.82** x ln(-ln(1- original risk))))
                = 1-exp(-exp(**-0.85**+**0.82** x ln(-ln(1- 0.2442))))
                = 0.1397 = 14%      

This seems to be the same as how the SCORE2 function from this package is calculated from.

However from Supplementary Methods Table 1, the rescaling factors for Female in low risk regions are  -0.52 (for Scale 1) and 1.01 (for Scale 2)

![image](https://github.com/dvicencio/RiskScorescvd/assets/9066508/886b30f8-0c4b-462a-8d07-2b8baac22f09)
If that is the case, I am wondering if the risk should be calculated like this instead

10-yr risk = 1-exp(-exp(**-0.52**+**1.01** x ln(-ln(1- original risk))))
                = 1-exp(-exp(**-0.52**+**1.01** x ln(-ln(1- 0.2442))))
                = 0.1515 = 15%   

Any thoughts on this ?

**Comment by rsantamariao** [comment]
Hi,
Agree with JauntyJJS.

2 issues:
1) The availability of RiskScorescvd to calculate SCORE2 risk represents a significant advancement in leveraging computational tools for cardiovascular disease (CVD) risk assessment. However, it's notable that this implementation does not account for the risk regions defined in the SCORE2 model, which is a critical aspect of its design. The SCORE2 model divides Europe into four risk regions (low, moderate, high, and very high risk) based on country-specific CVD mortality rates. This regional differentiation is vital for tailoring prevention strategies to specific populations, reflecting the varying levels of CVD risk across Europe. To enhance the utility and accuracy of RiskScorescvd for SCORE2 risk calculations, it would be advisable to update the library to incorporate these risk regions. This could involve adding a feature that allows users to specify the risk region or automatically determines it based on country input. Such an improvement would ensure that users can fully leverage SCORE2's capabilities for personalized risk assessment, thereby facilitating more precise and regionally tailored CVD prevention efforts (Reference and equations in supplemental materials of doi 10.1093/eurheartj/ehab309).

2) I highly recommend an enhancement that could significantly enhance the library's accuracy and clinical relevance. The inclusion of chronic kidney disease (CKD) measures, such as estimated glomerular filtration rate (eGFR) and albuminuria, into cardiovascular disease (CVD) risk assessments is supported by recent findings. Specifically, the study "Including measures of chronic kidney disease to improve cardiovascular risk prediction by SCORE2 and SCORE2-OP" published in the European Journal of Preventive Cardiology (2023) (doi 10.1093/eurjpc/zwac176) demonstrates that incorporating these CKD metrics into the SCORE2 and SCORE2-OP algorithms enhances their predictive capabilities. This adjustment allows for more nuanced risk stratification by accounting for CKD, a significant risk factor for CVD. By integrating these CKD measures into your library, users would benefit from more accurate risk predictions, enabling healthcare professionals to tailor prevention strategies more effectively to individual patient profiles. The equations and methodology for incorporating CKD measures can be found detailed in the referenced study, providing a clear guide for their integration into existing SCORE2 calculations.

I suggest to visit the SCORE2 CKD Add-on website calculator (https://ckdpcrisk.org/ckdpatchscore2). 

Thanks,

Best

**Comment by dvicencio** [comment]
Hi both,

I am delighted that the package is getting noticed, and it is of help. I have addressed the issue regarding the typo in the supplemental materials. 

Apologies; the package was initially developed for the UK population, but due to its international use and enthusiasm, I found some time to update the function. I have added the correct scales for each sex and also added the much-requested risk region alternative calculations. You can now choose which risk region you aim to calculate by using the "Risk.region" parameter/argument. 

Dear Dr. Santamaria,

Not really an issue but more of a request. I am currently swamped with other projects, but will get started with the incorporation of CKD measures. It is indeed important and will have a look at the attached paper.

Please note that the current updates are only available at the developing version of the package. I will submit to CRAN once I have added multiple other risk scores I am planning to incorporate. At the moment please use the following code to use the most updated package. 

```
install.packages("devtools")
devtools::install_github("dvicencio/RiskScorescvd")
```

Many thanks for your input and hope this works ok, otherwise please also let me know. 
Please also make sure you cite the package where appropriate. 

All the best,
Dan

**Comment by JauntyJJS** [comment]
Hi @dvicencio ,

Thank you for your patience.

I have tested the code using the example from the supplementary word document and it gives out the right value as the online calculator from ESC

``` r
female_score2_risk <- RiskScorescvd::SCORE2(
  Risk.region = "Low",
  Age = 75,
  Gender = "female",
  smoker = 1,
  systolic.bp = 140,
  diabetes = 0,
  total.chol = 5.5,
  total.hdl = 1.3,
  classify = FALSE
)

female_score2_risk
#> [1] 15

male_score2_risk <- RiskScorescvd::SCORE2(
  Risk.region = "Low",
  Age = 75,
  Gender = "male",
  smoker = 1,
  systolic.bp = 140,
  diabetes = 0,
  total.chol = 5.5,
  total.hdl = 1.3,
  classify = FALSE
)

male_score2_risk
#> [1] 19
```

<sup>Created on 2024-03-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

![Female Score2 Low Risk](https://github.com/dvicencio/RiskScorescvd/assets/9066508/ba1b22cc-4144-4e82-b0f0-43b894250ad6)

![Male Score2 Low Risk](https://github.com/dvicencio/RiskScorescvd/assets/9066508/b5c79315-2598-4864-be89-aec3bf547dc1)

I will proceed to close the issue.
