### ISSUE TITLE
Making a simple test unit for SCORE2

### ISSUE THREAD

**Issue by JauntyJJS** [dvicencio/RiskScorescvd#3]
Hi @dvicencio 

Thank you for the fix in the earlier issue.
May I have your permission to fork the repository and create a pull request for me to add some test units for SCORE2 ? Just in case the codes need to change and these test units will be helpful in ensuring that the values are still correct.

**Comment by dvicencio** [comment]
Hi Jeremy,

Absolutely, please go ahead.

Let me know if you encounter any issues; I am not sure what privacy settings I used, but I think you should be allowed to fork it, and I will only have to authorise the changes.

**Comment by JauntyJJS** [comment]
Since the branch has been merged, I will close the issue. Will open a new issue to start writing some test units for the function in 12_SCORE2_df.R .
